create database DUAN_NHOM4
go
USE DUAN_NHOM4
GO
-- LoaiSanPham
CREATE TABLE LOAISANPHAM(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MA VARCHAR(20) UNIQUE,
TEN NVARCHAR(30)
)
CREATE TABLE SIZE(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MA VARCHAR(20) UNIQUE,
TEN NVARCHAR(30)
)
CREATE TABLE THUONGHIEU(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MA VARCHAR(20) UNIQUE,
TEN NVARCHAR(30)
)
CREATE TABLE MAUSAC(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MA VARCHAR(20) UNIQUE,
TEN NVARCHAR(30)
)
-- SANPHAM
CREATE TABLE SANPHAM(
Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDLOAISP UNIQUEIDENTIFIER,
IDMAUSAC UNIQUEIDENTIFIER,
IDSIZE UNIQUEIDENTIFIER,
IDTHUONGHIEU UNIQUEIDENTIFIER,
MASP VARCHAR(20) UNIQUE,
TENSP NVARCHAR(50) DEFAULT NULL,
SOLUONG INT,
HINHANH NVARCHAR(50) DEFAULT NULL,
CHATLIEU NVARCHAR(50) DEFAULT NULL,
GIANHAP DECIMAL(20,0) DEFAULT 0,
GIABAN DECIMAL(20,0) DEFAULT 0
)

ALTER TABLE SANPHAM ADD FOREIGN KEY(IDLOAISP) REFERENCES LOAISANPHAM(ID)
ALTER TABLE SANPHAM ADD FOREIGN KEY(IDMAUSAC) REFERENCES MAUSAC(ID)
ALTER TABLE SANPHAM ADD FOREIGN KEY(IDSIZE) REFERENCES SIZE(ID)
ALTER TABLE SANPHAM ADD FOREIGN KEY(IDTHUONGHIEU) REFERENCES THUONGHIEU(ID)


-- NhanVien
CREATE TABLE NHANVIEN(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MANV VARCHAR(20) UNIQUE,
HOTEN NVARCHAR(30) DEFAULT NULL,
GIOITINH NVARCHAR(30) DEFAULT NULL,
NgaySinh DATE DEFAULT NULL,
DIACHI NVARCHAR(100) DEFAULT NULL,
EMAIL NVARCHAR(75) DEFAULT NULL,
SDT VARCHAR(30) DEFAULT NULL,
TENTAIKHOAN NVARCHAR(100) DEFAULT NULL,
MATKHAU VARCHAR(MAX) DEFAULT NULL,
HINHANH NVARCHAR(50) DEFAULT NULL,
TrangThai INT DEFAULT 0
)



--KhuyenMai

CREATE TABLE KHUYENMAI(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
MA VARCHAR(20) UNIQUE,
TENKM NVARCHAR(30),
NGAYBATDAU DATE DEFAULT NULL,
NGAYKETTHUC DATE DEFAULT NULL,
DIEUKIEN int,
PHANTRAMGIAM INT,
TrangThai INT DEFAULT 0,
)


CREATE TABLE TAIKHOANADMIN(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
TENTK NVARCHAR(30),
MATKHAU VARCHAR (MAX) DEFAULT NULL,
)



/*
CREATE FUNCTION AUTO_IDKH()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(10)
	IF (SELECT COUNT(MAHD) FROM HOADONMUAHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAHD, 3)) FROM HOADONMUAHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HD00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HD0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
*/
CREATE TABLE HOADONMUAHANG(
ID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
IDNV UNIQUEIDENTIFIER,
IDKM  UNIQUEIDENTIFIER,
MAHD NVARCHAR(5) CONSTRAINT IDHD DEFAULT DBO.AUTO_IDKH(),
NGAYTAOHOADON DATE DEFAULT NULL,
TONGTIEN DECIMAL(20,0) DEFAULT 0,
)

ALTER TABLE HOADONMUAHANG ADD FOREIGN KEY(IDNV) REFERENCES NHANVIEN(ID)
ALTER TABLE HOADONMUAHANG ADD FOREIGN KEY(IDKM) REFERENCES KHUYENMAI(ID)

CREATE TABLE HOADONCHITIET(
IDHOADONMUAHANG UNIQUEIDENTIFIER,
IDSP UNIQUEIDENTIFIER,
SoLuong INT,
DonGia DECIMAL(20,0) DEFAULT 0,
ThanhTien DECIMAL(20,0) DEFAULT 0,
CONSTRAINT PK_HOADONCHITIET PRIMARY KEY (IDHOADONMUAHANG,IDSP),
CONSTRAINT FK3 FOREIGN KEY(IDHOADONMUAHANG) REFERENCES HOADONMUAHANG(ID),
CONSTRAINT FK4 FOREIGN KEY(IDSP) REFERENCES SANPHAM(ID),
)

