/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DuAnNhom4_view;

import DuAnNhom4_model.LoaiSanPham;
import DuAnNhom4_model.MauSac;
import DuAnNhom4_model.Size;
import DuAnNhom4_model.ThuongHieu;
import DuAnNhom4_repository.LoaiSanPham_repository;
import DuAnNhom4_repository.MauSac_repository;
import DuAnNhom4_repository.SanPhamChiTiet_repository;
import DuAnNhom4_repository.Size_repository;
import DuAnNhom4_repository.ThuongHieu_repository;
import DuAnNhom4_service.Imp.LoaiSanPham_sevrice;
import DuAnNhom4_viewmodel.SanPhamChiTiet;
import com.barcodelib.barcode.Linear;
import java.awt.Image;
import java.io.File;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.print.attribute.standard.SheetCollate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class QuanLySanPham extends javax.swing.JPanel {

    private DefaultComboBoxModel molBox = new DefaultComboBoxModel();

    SanPhamChiTiet_repository SPCT = new SanPhamChiTiet_repository();
    ArrayList<SanPhamChiTiet> list;
    DefaultTableModel mol;
    String strHinhAnh = null;
    int index;
    private ThuongHieu_repository th;
    private MauSac_repository ms;
    private Size_repository s;
    private LoaiSanPham_repository l;

    public QuanLySanPham() {
        initComponents();
        fillToTable((ArrayList<SanPhamChiTiet>) SPCT.getAll());
        addLSP((ArrayList<LoaiSanPham>) l.getAllLoaiSP());
        addMS((ArrayList<MauSac>) ms.getAll());
        addSIZE((ArrayList<Size>) s.getAllSize());
        addTH((ArrayList<ThuongHieu>) th.getAll());

    }

    public void addLSP(ArrayList<LoaiSanPham> listSP) {
        cboLoai.removeAllItems();
        listSP = (ArrayList<LoaiSanPham>) LoaiSanPham_sevrice.getAllLoaiSP();
        for (int i = 0; i < listSP.size(); i++) {
            cboLoai.addItem(listSP.get(i).getTenLoai().toString());
        }

    }

    public void addTH(ArrayList<ThuongHieu> listSP) {
        cboThuongHieu.removeAllItems();
        listSP = (ArrayList<ThuongHieu>) ThuongHieu_repository.getAll();
        for (int i = 0; i < listSP.size(); i++) {
            cboThuongHieu.addItem(listSP.get(i).getTEN().toString());
        }

    }

    public void addMS(ArrayList<MauSac> listSP) {
        cboMauSac.removeAllItems();
        listSP = (ArrayList<MauSac>) MauSac_repository.getAll();
        for (int i = 0; i < listSP.size(); i++) {
            cboMauSac.addItem(listSP.get(i).getTENMAU().toString());
        }

    }

    public void addSIZE(ArrayList<Size> listSP) {
        cboSize.removeAllItems();
        listSP = (ArrayList<Size>) Size_repository.getAllSize();
        for (int i = 0; i < listSP.size(); i++) {
            cboSize.addItem(listSP.get(i).getTENSIZE().toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        btnLoaiSp = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        cboLoai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        txtGiaNhap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtChatLieu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        lblHinhAnh = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        cboMauSac = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboSize = new javax.swing.JComboBox<>();
        txtTenSP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiemTen = new javax.swing.JTextField();
        cboThuongHieu = new javax.swing.JComboBox<>();
        btnSize = new javax.swing.JButton();
        btnThuongHieu = new javax.swing.JButton();
        btnMauSac = new javax.swing.JButton();
        txtIDTH = new javax.swing.JLabel();
        txtIDsize = new javax.swing.JLabel();
        txtIDMS = new javax.swing.JLabel();
        txtIDLoai = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTable = new javax.swing.JTable();

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Giá bán :");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Loại SP :");

        btnSua.setBackground(new java.awt.Color(102, 102, 102));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnSua.setText("Sửa ");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLoaiSp.setBackground(new java.awt.Color(102, 102, 102));
        btnLoaiSp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoaiSp.setForeground(new java.awt.Color(255, 255, 255));
        btnLoaiSp.setText("Loại SP");
        btnLoaiSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSpActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Giá nhập :");

        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Số lượng : ");

        btnHuy.setBackground(new java.awt.Color(102, 102, 102));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/multiply.png"))); // NOI18N
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        cboLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiItemStateChanged(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(102, 102, 102));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sp.png"))); // NOI18N
        btnThem.setText("Thêm SP");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Size :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Màu sắc : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Chất liệu :");

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setToolTipText("");
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhAnhMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã SP : ");

        cboMauSac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboMauSacItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên SP :");

        cboSize.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSizeItemStateChanged(evt);
            }
        });

        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Thương hiệu :");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Tìm kiếm theo tên ");

        txtTimKiemTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemTenKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(1177, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtTimKiemTen, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtTimKiemTen, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1))
        );

        cboThuongHieu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThuongHieuItemStateChanged(evt);
            }
        });

        btnSize.setBackground(new java.awt.Color(102, 102, 102));
        btnSize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSize.setForeground(new java.awt.Color(255, 255, 255));
        btnSize.setText("Size");
        btnSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSizeActionPerformed(evt);
            }
        });

        btnThuongHieu.setBackground(new java.awt.Color(102, 102, 102));
        btnThuongHieu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThuongHieu.setForeground(new java.awt.Color(255, 255, 255));
        btnThuongHieu.setText("Thương hiệu ");
        btnThuongHieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThuongHieuActionPerformed(evt);
            }
        });

        btnMauSac.setBackground(new java.awt.Color(102, 102, 102));
        btnMauSac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMauSac.setForeground(new java.awt.Color(255, 255, 255));
        btnMauSac.setText("Màu sắc");
        btnMauSac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMauSacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(txtIDTH, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addGap(23, 23, 23)
                                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIDMS, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboMauSac, 0, 205, Short.MAX_VALUE)
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboLoai, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboThuongHieu, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addComponent(txtIDsize, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIDLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 1, Short.MAX_VALUE)
                                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSoLuong)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(txtGiaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnThuongHieu)
                            .addComponent(btnLoaiSp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSize, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMauSac, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnHuy)
                        .addComponent(btnSua)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(jLabel3)
                                .addComponent(txtIDLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDTH, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(cboThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtIDsize, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addGap(0, 18, Short.MAX_VALUE))
                                            .addComponent(txtIDMS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtGiaNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                        .addGap(15, 15, 15)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cboMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHuy))
                            .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnLoaiSp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnThuongHieu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSize)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMauSac)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/s (2).png"))); // NOI18N

        tblTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SP ", "Tên SP", "Loại SP", "Thương hiệu ", "Size", "Màu sắc", "Số lượng", "Chất liệu", "Giá nhập", "Giá bán", "Hình ảnh", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTable.setRowHeight(30);
        tblTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiItemStateChanged
        if (cboLoai.getItemCount() > 0) {
            String ID = cboLoai.getSelectedItem().toString();
            LoaiSanPham lsp = LoaiSanPham_repository.getLoaiSPbymaloai(ID);
            txtIDLoai.setText(lsp.getIDLoaiSanPham());
            fillToTable((ArrayList<SanPhamChiTiet>) SPCT.getAll());
        }
    }//GEN-LAST:event_cboLoaiItemStateChanged

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        SanPhamChiTiet vsp = getModel();
        try {

//            if (listVsp.isEmpty()) {
//                JOptionPane.showMessageDialog(this, "List ko còn dữ liệu để sửa");
//                return;
//            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            SanPhamChiTiet_repository.SUASPCT(vsp);
            fillToTable((ArrayList<SanPhamChiTiet>) SPCT.getAll());

            JOptionPane.showMessageDialog(this, "update thanh cong");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi update");
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        clearForm();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        SanPhamChiTiet vsp = getModel();

        try {
            if (check()) {
                int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm sản phẩm không");
                if (hoi != JOptionPane.YES_OPTION) {
                    return;
                }
                Linear barcode = new Linear();
                barcode.setType(Linear.CODE128B);
                barcode.setData(txtMaSP.getText());
//                barcode.setData(txtTenSP.getText());
                barcode.setI(11.0f);

                String fname = txtMaSP.getText();

                barcode.renderBarcode("D:\\" + fname + ".png");

                SanPhamChiTiet_repository.THEMSPCT(vsp);
                fillToTable((ArrayList<SanPhamChiTiet>) SPCT.getAll());
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi sửa");
            return;
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void lblHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhAnhMouseClicked
        try {
            JFileChooser jfc = new JFileChooser("C:\\Users\\Dell\\Desktop\\DUAN1\\src\\img");
            jfc.showOpenDialog(null);
            File fire = jfc.getSelectedFile();
            Image img = ImageIO.read(fire);
            strHinhAnh = fire.getName();
            lblHinhAnh.setText("");
            int width = lblHinhAnh.getWidth();
            int height = lblHinhAnh.getHeight();
            lblHinhAnh.setIcon(new ImageIcon(img.getScaledInstance(width, height, 0)));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblHinhAnhMouseClicked

    private void btnLoaiSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSpActionPerformed
        new LoaiSP().setVisible(true);
    }//GEN-LAST:event_btnLoaiSpActionPerformed

    private void cboThuongHieuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThuongHieuItemStateChanged
        if (cboThuongHieu.getItemCount() > 0) {
            String ID = cboThuongHieu.getSelectedItem().toString();
            ThuongHieu lsp = ThuongHieu_repository.getLoaiSPbymaloai(ID);
            txtIDTH.setText(lsp.getID());
            fillToTable((ArrayList<SanPhamChiTiet>) SPCT.getAll());
        }
    }//GEN-LAST:event_cboThuongHieuItemStateChanged

    private void btnSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSizeActionPerformed
        new QuanLySize().setVisible(true);

    }//GEN-LAST:event_btnSizeActionPerformed

    private void btnThuongHieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThuongHieuActionPerformed
        new QuanLyThuongHieu().setVisible(true);
    }//GEN-LAST:event_btnThuongHieuActionPerformed

    private void btnMauSacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMauSacActionPerformed
        new QuanLyMauSac().setVisible(true);

    }//GEN-LAST:event_btnMauSacActionPerformed

    private void cboSizeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSizeItemStateChanged
        if (cboSize.getItemCount() > 0) {
            String ID = cboSize.getSelectedItem().toString();
            Size lsp = Size_repository.getLoaiSPbymaloai(ID);
            txtIDsize.setText(lsp.getID());
            fillToTable((ArrayList<SanPhamChiTiet>) SPCT.getAll());
        }
    }//GEN-LAST:event_cboSizeItemStateChanged

    private void cboMauSacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboMauSacItemStateChanged
        if (cboMauSac.getItemCount() > 0) {
            String ID = cboMauSac.getSelectedItem().toString();
            MauSac lsp = MauSac_repository.getLoaiSPbymaloai(ID);
            txtIDMS.setText(lsp.getID());
            fillToTable((ArrayList<SanPhamChiTiet>) SPCT.getAll());
        }
    }//GEN-LAST:event_cboMauSacItemStateChanged

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed
    SanPhamChiTiet_repository vspsv = new SanPhamChiTiet_repository();
    private void txtTimKiemTenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemTenKeyPressed
        ArrayList<SanPhamChiTiet> listTim1 = (ArrayList<SanPhamChiTiet>) SanPhamChiTiet_repository.timKiemTen(txtTimKiemTen.getText());
        fillToTable(listTim1);

    }//GEN-LAST:event_txtTimKiemTenKeyPressed

    private void tblTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTableMouseClicked
        try {
            index = tblTable.getSelectedRow();
            showDetail((ArrayList<SanPhamChiTiet>) SanPhamChiTiet_repository.getAll());
        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(this, "Lỗi click");
        }
    }//GEN-LAST:event_tblTableMouseClicked

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLoaiSp;
    private javax.swing.JButton btnMauSac;
    private javax.swing.JButton btnSize;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThuongHieu;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboMauSac;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JComboBox<String> cboThuongHieu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JTable tblTable;
    private javax.swing.JTextField txtChatLieu;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtGiaNhap;
    private javax.swing.JLabel txtIDLoai;
    private javax.swing.JLabel txtIDMS;
    private javax.swing.JLabel txtIDTH;
    private javax.swing.JLabel txtIDsize;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiemTen;
    // End of variables declaration//GEN-END:variables

    private void fillToTable(ArrayList<SanPhamChiTiet> listVsp) {
        mol = (DefaultTableModel) tblTable.getModel();
        mol.setRowCount(0);
        for (int i = 0; i < listVsp.size(); i++) {
            Object[] data = new Object[]{listVsp.get(i).getMASP(), listVsp.get(i).getTENSP(), listVsp.get(i).getTENLOAI(), listVsp.get(i).getTENTHUONGHIEU(), listVsp.get(i).getTENSIZE(),
                listVsp.get(i).getTENMS(), listVsp.get(i).getSOLUONG(), listVsp.get(i).getCHATLIEU(), listVsp.get(i).getGIANHAP(),
                listVsp.get(i).getGIABAN(), listVsp.get(i).getHINHANH(), listVsp.get(i).TrangThai()};
            mol.addRow(data);
        }
    }

    private void showDetail(ArrayList<SanPhamChiTiet> list) {
        int row = tblTable.getSelectedRow();
        SanPhamChiTiet vsp = SanPhamChiTiet_repository.getAll().get(row);
        txtMaSP.setText(vsp.getMASP());
        txtTenSP.setText(vsp.getTENSP());
        txtSoLuong.setText(String.valueOf(vsp.getSOLUONG()));
        txtChatLieu.setText(vsp.getCHATLIEU());
        txtGiaNhap.setText(String.valueOf(vsp.getGIANHAP()));
        txtGiaBan.setText(String.valueOf(vsp.getGIABAN()));
        cboSize.setSelectedItem(vsp.getTENSIZE());
        cboMauSac.setSelectedItem(vsp.getTENMS());
        cboLoai.setSelectedItem(vsp.getTENLOAI());
        cboThuongHieu.setSelectedItem(vsp.getTENTHUONGHIEU());
        if (vsp.getHINHANH().equalsIgnoreCase("No Avatar")) {
            lblHinhAnh.setText("No Avatar");
            lblHinhAnh.setIcon(null);
        } else {
            lblHinhAnh.setText("");
            ImageIcon imgIcon = new ImageIcon(getClass().getResource("/img/" + vsp.getHINHANH()));
            Image img = imgIcon.getImage();
            int width = lblHinhAnh.getWidth();
            int height = lblHinhAnh.getHeight();
            img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
            lblHinhAnh.setIcon(imgIcon);
        }
    }

    public SanPhamChiTiet getModel() {

        SanPhamChiTiet vsp = new SanPhamChiTiet();
        vsp.setIDLOAISP(txtIDLoai.getText());
        vsp.setIDMAUSAC(txtIDMS.getText());
        vsp.setIDSIZE(txtIDsize.getText());
        vsp.setIDTHUONGHIEU(txtIDTH.getText());

        vsp.setMASP(txtMaSP.getText());
        vsp.setTENSP(txtTenSP.getText());
        vsp.setSOLUONG(Integer.parseInt(txtSoLuong.getText()));
        vsp.setCHATLIEU(txtChatLieu.getText());
        vsp.setGIANHAP(BigDecimal.valueOf(Double.valueOf(txtGiaNhap.getText())));
        vsp.setGIABAN(BigDecimal.valueOf(Double.valueOf(txtGiaBan.getText())));

        if (strHinhAnh == null) {
            vsp.setHINHANH("No Avatar");
        } else {
            vsp.setHINHANH(strHinhAnh);
        }
        return vsp;
    }

    private void clearForm() {
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtSoLuong.setText("");
        txtChatLieu.setText("");
        txtGiaNhap.setText("");
        txtGiaBan.setText("");
        lblHinhAnh.setIcon(null);

    }

    public boolean check() {
        if (txtMaSP.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã SP");
            return false;
        }
//        for (vSanPham vsp : listVsp) {
//            if (vsp.getMaSanPham().equalsIgnoreCase(txtMaSP.getText())) {
//                JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại");
//                return false;
//            }
//        }
        String ten = txtTenSP.getText();
        String Chatlieu = txtChatLieu.getText();
        
        if (txtTenSP.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Tên SP");
            return false;
        }else if(Integer.parseInt(ten) < 50){
            JOptionPane.showMessageDialog(this, "Không nhập quá 50 kí tự");
        }
        if (txtSoLuong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập số lượng");
            return false;
        }
        int soluong;
        try {
            soluong = Integer.parseInt(txtSoLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải nhập bằng số");
        }
        if (txtChatLieu.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Chất liệu");
            return false;
        }else if(Integer.parseInt(Chatlieu) < 50){
            JOptionPane.showMessageDialog(this, "Không nhập quá 50 kí tự");
        }

        if (txtGiaNhap.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập giá nhập");
            return false;
        }
        if (txtGiaBan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập giá bán");
            return false;
        }
        return true;
    }

}
