/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package DuAnNhom4_view;

import DuAnNhom4_model.KhuyenMai;
import DuAnNhom4_repository.KhuyenMai_repository;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class QuanLyKhuyenMai extends javax.swing.JPanel {

    List<KhuyenMai> list;
    DefaultTableModel mol;

    Date date = new Date();
    String pattern = "yyyy/MM/dd";
    SimpleDateFormat formatter = new SimpleDateFormat(pattern);


    int index;

    public QuanLyKhuyenMai() {
        initComponents();
//       setLocationRelativeTo(null);
        list = KhuyenMai_repository.getAllKM();
//        if (list.size() > 0) {
//            index = 0;
//            showDetail();
//        }
//        fillToTable();
        loadDataTblKhuyenMai();
//        fillToTable((ArrayList<vSanPham>) SP2.getAllVSP());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTenKM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgayBD = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNgayKT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtGG = new javax.swing.JTextField();
        txtDK = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnSuathongTin = new javax.swing.JButton();
        btnThemKM = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhuyenMai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã KM : ");

        txtMaKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên KM :");

        txtTenKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Ngày BĐ :");

        txtNgayBD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayBDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Ngày KT : ");

        txtNgayKT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgayKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayKTActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Phần Trăm Giảm : ");

        txtGG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDKActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Điều Kiện :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txtNgayBD)
                                    .addComponent(txtDK)
                                    .addComponent(txtGG))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(66, 66, 66)
                                .addComponent(txtTenKM, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenKM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDK, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtGG, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        btnSuathongTin.setBackground(new java.awt.Color(102, 102, 102));
        btnSuathongTin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuathongTin.setForeground(new java.awt.Color(255, 255, 255));
        btnSuathongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update.png"))); // NOI18N
        btnSuathongTin.setText("Sửa thông tin");
        btnSuathongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuathongTinActionPerformed(evt);
            }
        });

        btnThemKM.setBackground(new java.awt.Color(102, 102, 102));
        btnThemKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemKM.setForeground(new java.awt.Color(255, 255, 255));
        btnThemKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/sale-tag.png"))); // NOI18N
        btnThemKM.setText("Thêm KM");
        btnThemKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKMActionPerformed(evt);
            }
        });

        tblKhuyenMai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KM", "Tên KM", "Ngày BĐ", "Ngày KT", "Phần trăm giảm(%)", "Điều kiện (đồng)", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhuyenMai.setRowHeight(30);
        tblKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhuyenMai);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btnThemKM)
                .addGap(51, 51, 51)
                .addComponent(btnSuathongTin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuathongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemKM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/s (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuathongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuathongTinActionPerformed
        KhuyenMai km = getModel();
        try {

            if (list.isEmpty()) {
                JOptionPane.showMessageDialog(this, "List ko còn dữ liệu để sửa");
                return;
            }
            int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            KhuyenMai_repository.sưa(km);
             loadDataTblKhuyenMai();
            JOptionPane.showMessageDialog(this, "Sửa thành công");

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi update");
        }
    }//GEN-LAST:event_btnSuathongTinActionPerformed

    private void btnThemKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKMActionPerformed
        KhuyenMai km = getModel();
        try {
            if (check()) {

                KhuyenMai_repository.them(km);
                loadDataTblKhuyenMai();
                index = list.size() - 1;
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi sửa");
            return;
        }
    }//GEN-LAST:event_btnThemKMActionPerformed

    private void txtNgayBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayBDActionPerformed

    private void tblKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhuyenMaiMouseClicked
        try {
            index = tblKhuyenMai.getSelectedRow();
            showDetail();
        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(this, "Lỗi click");
        }
    }//GEN-LAST:event_tblKhuyenMaiMouseClicked

    private void txtNgayKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayKTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayKTActionPerformed

    private void txtDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDKActionPerformed
//    KhuyenMai km = new KhuyenMai();
    private TimKhuyenMai timMaUI;
//    vSanPham v = new vSanPham();
 
    private KhuyenMai_repository KM1;
    private int tongTien;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuathongTin;
    private javax.swing.JButton btnThemKM;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKhuyenMai;
    private javax.swing.JTextField txtDK;
    private javax.swing.JTextField txtGG;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtNgayKT;
    private javax.swing.JTextField txtTenKM;
    // End of variables declaration//GEN-END:variables

    private void showDetail() {
        KhuyenMai km = list.get(index);
        txtMaKM.setText(km.getMaKhuyenMai());
        txtTenKM.setText(km.getTenKhuyenMai());
        txtNgayBD.setText(formatter.format(km.getNgayBatDau()));
        txtNgayKT.setText(formatter.format(km.getNgayKetThuc()));
        txtGG.setText(String.valueOf(km.getPhantramgiam()));
        txtDK.setText(String.valueOf(km.getDieukien()));

    }

    private void fillToTable() {

        list = KhuyenMai_repository.getAllKM();
        mol = (DefaultTableModel) tblKhuyenMai.getModel();
        mol.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            Date now = new Date();
            Object[] data = new Object[]{list.get(i).getMaKhuyenMai(), list.get(i).getTenKhuyenMai(), list.get(i).getNgayBatDau(), list.get(i).getNgayKetThuc(), list.get(i).getPhantramgiam(),
                list.get(i).getDieukien()};
            mol.addRow(data);
        }
    }

    private void loadDataTblKhuyenMai() {
        list = KhuyenMai_repository.getAllKM();
        mol = (DefaultTableModel) tblKhuyenMai.getModel();
        mol.setRowCount(0);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        DecimalFormat dcf = new DecimalFormat(">###,###");
        for (KhuyenMai gg : list) {
            Vector vec = new Vector();
            vec.add(gg.getMaKhuyenMai());
            vec.add(gg.getTenKhuyenMai());
            vec.add(sdf.format(gg.getNgayBatDau()));
            vec.add(sdf.format(gg.getNgayKetThuc()));
            vec.add(gg.getPhantramgiam());
            vec.add(dcf.format(gg.getDieukien()));
            Date now = new Date();
            if (gg.getNgayBatDau().before(now) && gg.getNgayKetThuc().after(now)) {
                vec.add("Có hiệu lực");
            } else {
                vec.add("Không hiệu lực");
            }

            mol.addRow(vec);
        }
    }

    private void clearForm() {
        txtMaKM.setText("");
        txtTenKM.setText("");
        txtNgayBD.setText("0000/00/00");
        txtNgayKT.setText("0000/00/00");
    }

    private void showDetail(KhuyenMai km) {

        txtMaKM.setText(km.getMaKhuyenMai());
        txtTenKM.setText(km.getTenKhuyenMai());
        txtNgayBD.setText(formatter.format(km.getNgayBatDau()));
        txtNgayKT.setText(formatter.format(km.getNgayKetThuc()));
        txtGG.setText(String.valueOf(km.getPhantramgiam()));
        txtDK.setText(String.valueOf(km.getDieukien()));

    }

    public KhuyenMai getModel() {
        KhuyenMai km = new KhuyenMai();
        km.setMaKhuyenMai(txtMaKM.getText());
        km.setTenKhuyenMai(txtTenKM.getText());
        km.setDieukien(Integer.parseInt(txtDK.getText()));
        km.setPhantramgiam(Integer.parseInt(txtGG.getText()));
        try {
            km.setNgayBatDau(formatter.parse(txtNgayBD.getText()));
            km.setNgayKetThuc(formatter.parse(txtNgayKT.getText()));
        } catch (Exception e) {
        }

        return km;
    }

    private boolean check() {
        if (txtMaKM.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Mã khuyến mãi");
            return false;
        }
        for (KhuyenMai km : list) {
            if (km.getMaKhuyenMai().equalsIgnoreCase(txtMaKM.getText())) {
                JOptionPane.showMessageDialog(this, "Mã Khuyến mãi đã tồn tại");
                return false;
            }
        }
        if (txtTenKM.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Bạn chưa nhập Tên khuyến mãi");
            return false;
        }
        return true;
    }

   
}
